function start() {



  // Commands


  arrayfromjson = parseStringToGeojson(document.getElementById('input').value).features[0].geometry.coordinates
  console.log(arrayfromjson)


  fillingPointsInOrOutside(); //check whether the points are in- or outside the polygon
  fillingIntersectionIndexArray(); //check where the intersections are
  pointToPointDistances(); //calculate all distances
  subsequenceDistances(); //calculate the distances of the subaequences
  fillingResultTable(); // fill the resultTable
  resultTable.sort((a,b) => b[1]-a[1]); //Sort the resultTable
  convertArrayValues(resultTable); //convert the values in the resultTable




  //Display the results in console for debugging
  //console.log(leftBottomCorner); //Display constants in console
  //console.log(rightTopCorner);
  //console.table(pointsInOrOutsideArray); //Display arrays in console
  //console.table(intersectionIndexArray);
  //console.table(distancesPointToPoint);
  //console.table(distancesSubsequences);
  //console.log(totalDistance()); //Display total length
  //console.table(resultTable); //Display final result table

  //results to HTML

  document.getElementById("tbody").innerHTML = createTableHTML(resultTable); //Refers to the table body from the html-document. Inserts the code generated by the createTableHTML-function
  document.getElementById("pbody").innerHTML = "Total length: " + totalDistance() + " m"; //Refers to the paragraph of the html-document and creates the output for the total length

  return false
}
